# Generated by Django 3.2.7 on 2021-10-05 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('ssh', 'ssh')], max_length=10)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hosts.credentials')),
            ],
            options={
                'unique_together': {('ip_address', 'port', 'protocol')},
            },
        ),
    ]
