# Generated by Django 3.2.7 on 2021-10-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='json_data',
            new_name='sensors_data',
        ),
    ]
