volumes:
  database_data: {}

networks:
  backend:

services:
  database:
    container_name: database
    image: postgres
    networks:
      backend:
    volumes:
      - database_data:/var/lib/posgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  load_balancer:
    container_name: load_balancer
    build: 
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
  api:
    container_name: api 
    image: grimsleepless/ideal-octo-telegram
    networks:
      backend:
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
    depends_on:
      - database
