volumes:
  database_data: {}

networks:
  backend:
  outside:

services:
  database:
    container_name: database
    image: postgres
    networks:
      backend:
    volumes:
      - database_data:/var/lib/posgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  load_balancer:
    container_name: load_balancer
    image: grimsleepless/ideal-octo-telegram_nginx
    build: 
      context: docker/.
      dockerfile: Dockerfile.nginx
    networks:
      outside:
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy
  api:
    container_name: api 
    image: grimsleepless/ideal-octo-telegram
    networks:
      backend:
      outside:
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
    depends_on:
      - database
