[tool.poetry]
name = "Ideal Octo Telegram"
version = "0.1.0"
description = ""
authors = ["Jeff Labonte <grimsleepless@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.9"
djangorestframework = "^3.12.4"
paramiko = "^2.8.1"
celery = "^5.2.1"
pgsql = "^1.2"
dj-rest-auth = "^2.1.11"
django-allauth = "^0.46.0"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.1"
django-cors-headers = "^3.10.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = "^21.11b1"
flake8 = "^4.0.1"
isort = "^5.10.1"
pre-commit = "^2.15.0"
pynvim = "^0.4.3"
pytest-django = "^4.4.0"
pytest-testdox = "^2.0.1"
factory-boy = "^3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max_length = 160

[tool.black]
target-version = ["py38",]
include = '\.pyi?$'
line-length = 120
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black" 
multi_line_output = 3

[tool.pyright]
python.analysis.autoImportCompletions = true
