# Generated by Django 3.2.7 on 2021-09-20 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mushroomsensors',
            name='device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mushroom_sensors.device'),
        ),
    ]
