# Generated by Django 4.0 on 2021-12-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_report", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorreport",
            old_name="type",
            new_name="value_type",
        ),
    ]
