# Generated by Django 3.2.8 on 2021-10-25 03:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gateway", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                (
                    "type",
                    models.CharField(choices=[("humidity", "humidity"), ("temperature", "temperature")], max_length=30),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_sensors",
                        to="gateway.gateway",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
