# Generated by Django 3.2.8 on 2021-11-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
