services:
  dev_db:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: always
    ports:
      - 5432:5432
  message_broker:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.message_broker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
