# Generated by Django 3.2.8 on 2021-10-17 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("plant", "plant"), ("room", "room")], max_length=10)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
